version: '3.8'

services:
  register-of-equipment-postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=register-of-equipment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "db-data:/var/lib/register-of-equipment/data"

volumes:
  db-data: